name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    container:
      image: node:12-slim
    steps:
      - uses: actions/checkout@v2
      - name: Install npm modules
        run: npm i
      - name: Scan project for vulnerabilities
        run: npm audit
      - name: Check licenses
        run: npm run check-licenses
      - name: Run test suite
        run: npm t
      - name: Run build
        run: npm run build
